export const AIRPORT_MAP: Record<string, { city: string; name: string }> = {
    DEL: { city: "New Delhi", name: "Indira Gandhi International Airport" },
    BOM: { city: "Mumbai", name: "Chhatrapati Shivaji Maharaj International Airport" },
    BLR: { city: "Bengaluru", name: "Kempegowda International Airport" },
    HYD: { city: "Hyderabad", name: "Rajiv Gandhi International Airport" },
    MAA: { city: "Chennai", name: "Chennai International Airport" },
    CCU: { city: "Kolkata", name: "Netaji Subhash Chandra Bose International Airport" },
    AMD: { city: "Ahmedabad", name: "Sardar Vallabhbhai Patel International Airport" },
    PNQ: { city: "Pune", name: "Pune Airport" },
    GOI: { city: "Goa", name: "Dabolim Airport" },
    JAI: { city: "Jaipur", name: "Jaipur International Airport" },
    SXR: { city: "Srinagar", name: "Sheikh Ul-Alam International Airport" },
    COK: { city: "Kochi", name: "Cochin International Airport" },
    TRV: { city: "Thiruvananthapuram", name: "Trivandrum International Airport" },
    IXC: { city: "Chandigarh", name: "Shaheed Bhagat Singh International Airport" },
    ATQ: { city: "Amritsar", name: "Sri Guru Ram Dass Jee International Airport" },
    LKO: { city: "Lucknow", name: "Chaudhary Charan Singh International Airport" },
    VNS: { city: "Varanasi", name: "Lal Bahadur Shastri International Airport" },
    PAT: { city: "Patna", name: "Jay Prakash Narayan Airport" },
    BBI: { city: "Bhubaneswar", name: "Biju Patnaik International Airport" },
    GAU: { city: "Guwahati", name: "Lokpriya Gopinath Bordoloi International Airport" },
    IXB: { city: "Bagdogra", name: "Bagdogra Airport" },
    UDR: { city: "Udaipur", name: "Maharana Pratap Airport" },
    JDH: { city: "Jodhpur", name: "Jodhpur Airport" },
    IXZ: { city: "Port Blair", name: "Veer Savarkar International Airport" },
    BDQ: { city: "Vadodara", name: "Vadodara Airport" },
    NAG: { city: "Nagpur", name: "Dr. Babasaheb Ambedkar International Airport" },
    IDR: { city: "Indore", name: "Devi Ahilya Bai Holkar Airport" },
    CJB: { city: "Coimbatore", name: "Coimbatore International Airport" },
    IXE: { city: "Mangalore", name: "Mangalore International Airport" },
    VTZ: { city: "Visakhapatnam", name: "Visakhapatnam Airport" },
    BHO: { city: "Bhopal", name: "Raja Bhoj Airport" },
    RPR: { city: "Raipur", name: "Swami Vivekananda Airport" },
    DXB: { city: "Dubai", name: "Dubai International Airport" },
    SIN: { city: "Singapore", name: "Changi Airport" },
    BKK: { city: "Bangkok", name: "Suvarnabhumi Airport" },
    LHR: { city: "London", name: "Heathrow Airport" },
    JFK: { city: "New York", name: "John F. Kennedy International Airport" },
    CDG: { city: "Paris", name: "Charles de Gaulle Airport" },
    HND: { city: "Tokyo", name: "Haneda Airport" },
    HKG: { city: "Hong Kong", name: "Hong Kong International Airport" },
    KUL: { city: "Kuala Lumpur", name: "Kuala Lumpur International Airport" },
    IST: { city: "Istanbul", name: "Istanbul Airport" },
    DOH: { city: "Doha", name: "Hamad International Airport" },
    AUH: { city: "Abu Dhabi", name: "Abu Dhabi International Airport" },
    AMS: { city: "Amsterdam", name: "Schiphol Airport" },
    FRA: { city: "Frankfurt", name: "Frankfurt Airport" },
    MUC: { city: "Munich", name: "Munich Airport" },
    ZRH: { city: "Zurich", name: "Zurich Airport" },
    YYZ: { city: "Toronto", name: "Toronto Pearson International Airport" },
    SFO: { city: "San Francisco", name: "San Francisco International Airport" },
    MEL: { city: "Melbourne", name: "Melbourne Airport" },
    SYD: { city: "Sydney", name: "Sydney Kingsford Smith Airport" },
    MLE: { city: "Male", name: "Velana International Airport" },
    DPS: { city: "Bali", name: "Ngurah Rai International Airport" },
    HKT: { city: "Phuket", name: "Phuket International Airport" },
};
