import type { BusCity } from './types';

/**
 * Bus city directory shortcuts. Codes are Embark v9 city ids as stored in the
 * bus server's City collection (verified against the live directory on
 * 24 Sep 2026). Any other city can still be picked through the live search.
 */
export const BUS_CITIES: Record<string, BusCity> = {
    delhi: { code: 2754, name: 'Delhi', state: 'Delhi' },
    mumbai: { code: 1213, name: 'Mumbai', state: 'Maharashtra' },
    bangalore: { code: 4, name: 'Bangalore', state: 'Karnataka' },
    hyderabad: { code: 9, name: 'Hyderabad', state: 'Telangana' },
    chennai: { code: 185, name: 'Chennai', state: 'Tamil Nadu' },
    pune: { code: 1167, name: 'Pune', state: 'Maharashtra' },
    kolkata: { code: 2431, name: 'Kolkata', state: 'West Bengal' },
    ahmedabad: { code: 2164, name: 'Ahmedabad', state: 'Gujarat' },
    goa: { code: 1148, name: 'Goa', state: 'Goa' },
    jaipur: { code: 2596, name: 'Jaipur', state: 'Rajasthan' },
    lucknow: { code: 2483, name: 'Lucknow', state: 'Uttar Pradesh' },
    indore: { code: 2262, name: 'Indore', state: 'Madhya Pradesh' },
    bhopal: { code: 2270, name: 'Bhopal', state: 'Madhya Pradesh' },
    nagpur: { code: 1252, name: 'Nagpur', state: 'Maharashtra' },
    surat: { code: 2162, name: 'Surat', state: 'Gujarat' },
    manali: { code: 2118, name: 'Manali', state: 'Himachal Pradesh' },
    shimla: { code: 2129, name: 'Shimla', state: 'Himachal Pradesh' },
    chandigarh: { code: 2081, name: 'Chandigarh', state: 'Chandigarh' },
    dehradun: { code: 2393, name: 'Dehradun', state: 'Uttarakhand' },
    haridwar: { code: 2386, name: 'Haridwar', state: 'Uttarakhand' },
    rishikesh: { code: 2388, name: 'Rishikesh', state: 'Uttarakhand' },
    nainital: { code: 2389, name: 'Nainital', state: 'Uttarakhand' },
    mussoorie: { code: 2391, name: 'Mussoorie', state: 'Uttarakhand' },
    agra: { code: 2456, name: 'Agra', state: 'Uttar Pradesh' },
    varanasi: { code: 2485, name: 'Varanasi', state: 'Uttar Pradesh' },
    mathura: { code: 2489, name: 'Mathura', state: 'Uttar Pradesh' },
    ayodhya: { code: 3790, name: 'Ayodhya', state: 'Uttar Pradesh' },
    amritsar: { code: 2543, name: 'Amritsar', state: 'Punjab' },
    ludhiana: { code: 2539, name: 'Ludhiana', state: 'Punjab' },
    jalandhar: { code: 2541, name: 'Jalandhar', state: 'Punjab' },
    udaipur: { code: 3574, name: 'Udaipur', state: 'Rajasthan' },
    jodhpur: { code: 2619, name: 'Jodhpur', state: 'Rajasthan' },
    ajmer: { code: 2598, name: 'Ajmer', state: 'Rajasthan' },
    jaisalmer: { code: 2621, name: 'Jaisalmer', state: 'Rajasthan' },
    bikaner: { code: 2606, name: 'Bikaner', state: 'Rajasthan' },
    'mount-abu': { code: 2614, name: 'Mount Abu', state: 'Rajasthan' },
    shirdi: { code: 1185, name: 'Shirdi', state: 'Maharashtra' },
    nashik: { code: 1187, name: 'Nashik', state: 'Maharashtra' },
    kolhapur: { code: 5014, name: 'Kolhapur', state: 'Maharashtra' },
    mahabaleshwar: { code: 1189, name: 'Mahabaleshwar', state: 'Maharashtra' },
    solapur: { code: 1298, name: 'Solapur', state: 'Maharashtra' },
    satara: { code: 1183, name: 'Satara', state: 'Maharashtra' },
    lonavala: { code: 1313, name: 'Lonavala', state: 'Maharashtra' },
    vadodara: { code: 2180, name: 'Vadodara', state: 'Gujarat' },
    rajkot: { code: 2160, name: 'Rajkot', state: 'Gujarat' },
    bhavnagar: { code: 2172, name: 'Bhavnagar', state: 'Gujarat' },
    jamnagar: { code: 2227, name: 'Jamnagar', state: 'Gujarat' },
    dwarka: { code: 2231, name: 'Dwarka', state: 'Gujarat' },
    somnath: { code: 2239, name: 'Somnath', state: 'Gujarat' },
    ujjain: { code: 2271, name: 'Ujjain', state: 'Madhya Pradesh' },
    jabalpur: { code: 2288, name: 'Jabalpur', state: 'Madhya Pradesh' },
    gwalior: { code: 2321, name: 'Gwalior', state: 'Madhya Pradesh' },
    mysore: { code: 911, name: 'Mysore', state: 'Karnataka' },
    mangalore: { code: 909, name: 'Mangaluru', state: 'Karnataka' },
    hubli: { code: 2926, name: 'Hubli', state: 'Karnataka' },
    udupi: { code: 965, name: 'Udupi', state: 'Karnataka' },
    davangere: { code: 1106, name: 'Davanagere', state: 'Karnataka' },
    belagavi: { code: 1100, name: 'Belagavi', state: 'Karnataka' },
    hampi: { code: 1486, name: 'Hampi', state: 'Karnataka' },
    gokarna: { code: 1026, name: 'Gokarna', state: 'Karnataka' },
    chikmagalur: { code: 1405, name: 'Chikmagalur', state: 'Karnataka' },
    coimbatore: { code: 199, name: 'Coimbatore', state: 'Tamil Nadu' },
    madurai: { code: 189, name: 'Madurai', state: 'Tamil Nadu' },
    pondicherry: { code: 1164, name: 'Pondicherry', state: 'Puducherry' },
    tirupati: { code: 3376, name: 'Tirupati', state: 'Andhra Pradesh' },
    vellore: { code: 481, name: 'Vellore', state: 'Tamil Nadu' },
    salem: { code: 3305, name: 'Salem', state: 'Tamil Nadu' },
    ooty: { code: 3637, name: 'Ooty', state: 'Tamil Nadu' },
    kodaikanal: { code: 216, name: 'Kodaikanal', state: 'Tamil Nadu' },
    tirunelveli: { code: 455, name: 'Tirunelveli', state: 'Tamil Nadu' },
    nagercoil: { code: 449, name: 'Nagercoil', state: 'Tamil Nadu' },
    thanjavur: { code: 210, name: 'Thanjavur', state: 'Tamil Nadu' },
    erode: { code: 234, name: 'Erode', state: 'Tamil Nadu' },
    vijayawada: { code: 16, name: 'Vijayawada', state: 'Andhra Pradesh' },
    visakhapatnam: { code: 27, name: 'Visakhapatnam', state: 'Andhra Pradesh' },
    rajahmundry: { code: 191, name: 'Rajahmundry', state: 'Andhra Pradesh' },
    nellore: { code: 13, name: 'Nellore', state: 'Andhra Pradesh' },
    kurnool: { code: 11, name: 'Kurnool', state: 'Andhra Pradesh' },
    kochi: { code: 938, name: 'Ernakulam (Kochi)', state: 'Kerala' },
    trivandrum: { code: 3651, name: 'Thiruvananthapuram', state: 'Kerala' },
    kozhikode: { code: 1323, name: 'Kozhikode', state: 'Kerala' },
    thrissur: { code: 1244, name: 'Thrissur', state: 'Kerala' },
    munnar: { code: 1079, name: 'Munnar', state: 'Kerala' },
    digha: { code: 2427, name: 'Digha', state: 'West Bengal' },
    siliguri: { code: 2407, name: 'Siliguri', state: 'West Bengal' },
    puri: { code: 934, name: 'Puri', state: 'Odisha' },
    bhubaneswar: { code: 930, name: 'Bhubaneswar', state: 'Odisha' },
    patna: { code: 2024, name: 'Patna', state: 'Bihar' },
    gaya: { code: 2040, name: 'Gaya', state: 'Bihar' },
    muzaffarpur: { code: 2102, name: 'Muzaffarpur', state: 'Bihar' },
    ranchi: { code: 2591, name: 'Ranchi', state: 'Jharkhand' },
    jamshedpur: { code: 2592, name: 'Jamshedpur', state: 'Jharkhand' },
    guwahati: { code: 2003, name: 'Guwahati', state: 'Assam' },
};

/** Shown as chips in the city picker before the user types. */
export const POPULAR_BUS_CITIES: BusCity[] = [
    'delhi', 'mumbai', 'bangalore', 'hyderabad', 'chennai', 'pune', 'kolkata', 'ahmedabad',
    'goa', 'jaipur', 'lucknow', 'indore', 'chandigarh', 'manali', 'shirdi', 'surat',
].map((k) => BUS_CITIES[k]);

export const cityBySlug = (slug: string): BusCity | undefined => BUS_CITIES[slug];

export const slugOfCity = (name: string) =>
    name.toLowerCase().replace(/\(.*?\)/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
