export const airports = [
    // Top Metros (India)
    { code: 'DEL', city: 'New Delhi', airport: 'Indira Gandhi International Airport', country: 'India' },
    { code: 'BOM', city: 'Mumbai', airport: 'Chhatrapati Shivaji Maharaj International Airport', country: 'India' },
    { code: 'BLR', city: 'Bengaluru', airport: 'Kempegowda International Airport', country: 'India' },
    { code: 'MAA', city: 'Chennai', airport: 'Chennai International Airport', country: 'India' },
    { code: 'CCU', city: 'Kolkata', airport: 'Netaji Subhash Chandra Bose International Airport', country: 'India' },
    { code: 'HYD', city: 'Hyderabad', airport: 'Rajiv Gandhi International Airport', country: 'India' },

    // Top International
    { code: 'DXB', city: 'Dubai', airport: 'Dubai International Airport', country: 'UAE' },
    { code: 'JFK', city: 'New York', airport: 'John F. Kennedy International Airport', country: 'USA' },
    { code: 'LHR', city: 'London', airport: 'Heathrow Airport', country: 'UK' },
    { code: 'SIN', city: 'Singapore', airport: 'Changi Airport', country: 'Singapore' },
    { code: 'CDG', city: 'Paris', airport: 'Charles de Gaulle Airport', country: 'France' },
    { code: 'HND', city: 'Tokyo', airport: 'Haneda Airport', country: 'Japan' },
    { code: 'SYD', city: 'Sydney', airport: 'Kingsford Smith Airport', country: 'Australia' },
    { code: 'BKK', city: 'Bangkok', airport: 'Suvarnabhumi Airport', country: 'Thailand' },
    { code: 'YYZ', city: 'Toronto', airport: 'Pearson International Airport', country: 'Canada' },

    // Other Major Indian Airports
    { code: 'AMD', city: 'Ahmedabad', airport: 'Sardar Vallabhbhai Patel International Airport', country: 'India' },
    { code: 'COK', city: 'Kochi', airport: 'Cochin International Airport', country: 'India' },
    { code: 'GOI', city: 'Goa (Dabolim)', airport: 'Dabolim Airport', country: 'India' },
    { code: 'GOX', city: 'Goa (Mopa)', airport: 'Manohar International Airport', country: 'India' },
    { code: 'PNQ', city: 'Pune', airport: 'Pune Airport', country: 'India' },
    { code: 'GAU', city: 'Guwahati', airport: 'Lokpriya Gopinath Bordoloi International Airport', country: 'India' },
    { code: 'JAI', city: 'Jaipur', airport: 'Jaipur International Airport', country: 'India' },
    { code: 'LKO', city: 'Lucknow', airport: 'Chaudhary Charan Singh International Airport', country: 'India' },
    { code: 'TRV', city: 'Thiruvananthapuram', airport: 'Thiruvananthapuram International Airport', country: 'India' },
    { code: 'BBI', city: 'Bhubaneswar', airport: 'Biju Patnaik International Airport', country: 'India' },
    { code: 'CCJ', city: 'Kozhikode', airport: 'Calicut International Airport', country: 'India' },
    { code: 'SXR', city: 'Srinagar', airport: 'Sheikh ul-Alam International Airport', country: 'India' },
    { code: 'IDR', city: 'Indore', airport: 'Devi Ahilya Bai Holkar Airport', country: 'India' },
    { code: 'IXC', city: 'Chandigarh', airport: 'Shaheed Bhagat Singh International Airport', country: 'India' },
    { code: 'NAG', city: 'Nagpur', airport: 'Dr. Babasaheb Ambedkar International Airport', country: 'India' },
    { code: 'VNS', city: 'Varanasi', airport: 'Lal Bahadur Shastri International Airport', country: 'India' },
    { code: 'PAT', city: 'Patna', airport: 'Jay Prakash Narayan Airport', country: 'India' },
    { code: 'IXB', city: 'Bagdogra', airport: 'Bagdogra Airport', country: 'India' },
    { code: 'ATQ', city: 'Amritsar', airport: 'Sri Guru Ram Dass Jee International Airport', country: 'India' },
    { code: 'VTZ', city: 'Visakhapatnam', airport: 'Visakhapatnam Airport', country: 'India' },
    { code: 'RPR', city: 'Raipur', airport: 'Swami Vivekananda Airport', country: 'India' },
    { code: 'IXM', city: 'Madurai', airport: 'Madurai Airport', country: 'India' },
    { code: 'IXR', city: 'Ranchi', airport: 'Birsa Munda Airport', country: 'India' },
    { code: 'CJB', city: 'Coimbatore', airport: 'Coimbatore International Airport', country: 'India' },
    { code: 'UDR', city: 'Udaipur', airport: 'Maharana Pratap Airport', country: 'India' },
    { code: 'JDH', city: 'Jodhpur', airport: 'Jodhpur Airport', country: 'India' },
    { code: 'VGA', city: 'Vijayawada', airport: 'Vijayawada Airport', country: 'India' },
    { code: 'TRZ', city: 'Tiruchirappalli', airport: 'Tiruchirappalli International Airport', country: 'India' },
    { code: 'IXE', city: 'Mangaluru', airport: 'Mangaluru International Airport', country: 'India' },
    { code: 'IXJ', city: 'Jammu', airport: 'Jammu Civil Enclave', country: 'India' },
    { code: 'IXA', city: 'Agartala', airport: 'Maharaja Bir Bikram Airport', country: 'India' },
    { code: 'STV', city: 'Surat', airport: 'Surat Airport', country: 'India' },
    { code: 'BHO', city: 'Bhopal', airport: 'Raja Bhoj Airport', country: 'India' },
    { code: 'BDQ', city: 'Vadodara', airport: 'Vadodara Airport', country: 'India' },
    { code: 'IMF', city: 'Imphal', airport: 'Bir Tikendrajit International Airport', country: 'India' },
    { code: 'DIB', city: 'Dibrugarh', airport: 'Dibrugarh Airport', country: 'India' },
    { code: 'DMU', city: 'Dimapur', airport: 'Dimapur Airport', country: 'India' },
    { code: 'AJL', city: 'Aizawl', airport: 'Lengpui Airport', country: 'India' },
    { code: 'JRH', city: 'Jorhat', airport: 'Jorhat Airport', country: 'India' },
    { code: 'IXS', city: 'Silchar', airport: 'Silchar Airport', country: 'India' },
    { code: 'TEZ', city: 'Tezpur', airport: 'Tezpur Airport', country: 'India' },
    { code: 'IXI', city: 'Lilabari', airport: 'Lilabari Airport', country: 'India' },
    { code: 'SHL', city: 'Shillong', airport: 'Shillong Airport', country: 'India' },
    { code: 'IXZ', city: 'Port Blair', airport: 'Veer Savarkar International Airport', country: 'India' },
    { code: 'IXL', city: 'Leh', airport: 'Kushok Bakula Rimpochee Airport', country: 'India' },
    { code: 'DED', city: 'Dehradun', airport: 'Jolly Grant Airport', country: 'India' },
    { code: 'AGX', city: 'Agatti', airport: 'Agatti Airport', country: 'India' },
    { code: 'IXD', city: 'Prayagraj', airport: 'Prayagraj Airport', country: 'India' },
    { code: 'HSR', city: 'Rajkot', airport: 'Hirasar Airport', country: 'India' },
    { code: 'BKB', city: 'Bikaner', airport: 'Nal Airport', country: 'India' },
    { code: 'JSA', city: 'Jaisalmer', airport: 'Jaisalmer Airport', country: 'India' },
    { code: 'ISK', city: 'Nashik', airport: 'Nashik Airport', country: 'India' },
    { code: 'SAG', city: 'Shirdi', airport: 'Shirdi Airport', country: 'India' },
    { code: 'DHM', city: 'Dharamshala', airport: 'Kangra Airport', country: 'India' },
    { code: 'GWL', city: 'Gwalior', airport: 'Rajmata Vijaya Raje Scindia Air Terminal', country: 'India' },
    { code: 'JLR', city: 'Jabalpur', airport: 'Jabalpur Airport', country: 'India' },
    { code: 'MYQ', city: 'Mysuru', airport: 'Mysore Airport', country: 'India' },
    { code: 'HBX', city: 'Hubballi', airport: 'Hubballi Airport', country: 'India' },
    { code: 'IXG', city: 'Belagavi', airport: 'Belagavi Airport', country: 'India' },
    { code: 'GOP', city: 'Gorakhpur', airport: 'Mahayogi Gorakhnath Airport', country: 'India' },
    { code: 'TIR', city: 'Tirupati', airport: 'Tirupati Airport', country: 'India' },
    { code: 'RJA', city: 'Rajahmundry', airport: 'Rajahmundry Airport', country: 'India' },
    { code: 'KDP', city: 'Kadapa', airport: 'Kadapa Airport', country: 'India' },
];
